<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Welcome back_icon-input eye-password_1</name>
   <tag></tag>
   <elementGuidId>845e691a-c5a3-48c6-9292-75277f6cfabe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.icon-input.eye-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div[3]/div/form/div[2]/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bb3c4190-e2b9-406a-8987-6a127acf8a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-input eye-password</value>
      <webElementGuid>0b7d0160-e154-40ce-8cc0-c178f3e9d525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/feb_sign_up/eye-slash.svg</value>
      <webElementGuid>c877186d-4a67-40cb-af14-77b7ddb699fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Katalon Products</value>
      <webElementGuid>6a57bce0-b243-4f20-a77b-462347b0d91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>af66aff7-cc41-4ead-aeef-12775a4673ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;SignIn_wrapSignIn__jdoQJ&quot;]/div[@class=&quot;sign_up_section&quot;]/div[@class=&quot;sign_up_form&quot;]/form[@class=&quot;form_sign_up&quot;]/div[@class=&quot;input-div-form password-input&quot;]/img[@class=&quot;icon-input eye-password&quot;]</value>
      <webElementGuid>3a08c766-dbd3-4b5b-b330-9b834c86021a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div[3]/div/form/div[2]/img[2]</value>
      <webElementGuid>e6e811d1-5a02-43ac-8502-a78c1795eb41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Katalon Products'])[3]</value>
      <webElementGuid>d2a8168a-f370-460a-b1cd-d9fccbb2b427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img[2]</value>
      <webElementGuid>9bdc2228-8948-44e9-8d0d-053c3c1d31ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/feb_sign_up/eye-slash.svg' and @alt = 'Katalon Products']</value>
      <webElementGuid>c45e0174-b9c6-44ff-a1a2-062ccfd6ed10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
